image: golang:alpine
stages:
  - build
  - test
build:
  stage: build
  script:
    - apk add --update git
    - go get -v github.com/mitchellh/gox
    - mkdir binaries
    - gox -verbose --os="darwin linux windows" --arch="amd64"
    - mv gw_* binaries
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    paths:
     - binaries/
test:
  stage: test
  script:
    - go test -v