sudo: false
language: go
env:
- GO111MODULE=on
go:
- 1.12.x
script:
- make release
deploy:
  provider: releases
  api_key:
    secure: biKJxyK86a4BrnmHWEDiUKMivVQH31q9OjLCfuPJtv5+EziRZpjcg1CbWIfv1BQUgBNz+rnH2nZvtIB56T+VmQni+cv/c7MyTOCT5dKlG2hubaXPrTZMcuCKhFJnwHPq/501Bvb25mNWnKUqz56kcut00w7HuHCE8RuNTIpelYfaN7TRZd2b3Nzz/UtuM/66Kuuef29eB7UJMmhzdwAq1wAldpI3ALO/8Aq5kLeO0Djx/yeBHOkU9aDyKpQ+KHpx1RAbS7bzPDJvR/GLNscL6r7L6XG7K4smkSpdeLlOVZzcR0bd77kmu0jYgYOh+2Jc3mKbzqDKx1GD/ayH8oVx6klULzA7b0vy8VSArg8wCZAGPeVxzcSPb71xT4OVc2eBcwWsKDgYbT5NUzaqgLKizjTNdlqzIime3288i67hMOp4YOis/o1cDpHUio/HVfnZBPHEVuF1IoJ7mywy7CxuuRxoTEtduzAPnKvOLClyBws0AkBoavZmCJ1mNBBlyHW32m1qHFlvhItk8l0GWzq1hg1cKFsI0cqDQbKpIJbboBvu7Ly4VfUklazPGHOYLdV28k7rfwkrQRqtAOWL1/yeSfz/e+66wpvqiq5i9h+7NeLH97Pesh0jDDk57/X8MVq7lSzMrJ3444Ia+yZFlXdxTocgncV36yAx2kW7jAmWujs=
  file_glob: true
  file: build/binaries/*
  skip_cleanup: true
  on:
    tags: true
